/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: K- (https://sketchfab.com/K-)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/gojo-wip-40df4edf1b624b0b97da097e9b5b85c5
Title: Gojo WIP
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Gojo = (props) => {
  const { nodes, materials } = useGLTF("/models/gojo.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.026, -0.122, -0.001]}
        rotation={[0, 0, -1.504]}
        scale={0.365}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.ears}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Outline_black}
        />
      </group>
      <group
        position={[0.053, -0.395, 0.068]}
        rotation={[0, 0, -1.415]}
        scale={[1.266, 1.13, 1.126]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials["hair.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials["Outline_purple.003"]}
        />
      </group>
      <group rotation={[0, 0, -1.484]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.hairnet}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.Outline_black}
        />
      </group>
      <group
        position={[-0.034, 0, -0.001]}
        rotation={[Math.PI / 2, 0.098, 0]}
        scale={[1, 0.961, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.face}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.face}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.face}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.Outline_face}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials.Outline_face}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.Outline_face}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.mouth}
        />
      </group>
      <group
        position={[0.011, -0.22, -0.04]}
        rotation={[Math.PI / 2, 0.128, Math.PI / 2]}
        scale={[0.999, 1.067, 1.109]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_31.geometry}
          material={materials.headband}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.Outline}
        />
      </group>
      <group
        position={[0.055, -0.47, 0.251]}
        rotation={[-Math.PI / 2, 1.48, 1.716]}
        scale={[10.171, 12.781, 14.283]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_36.geometry}
          material={materials.tongue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials.Outline_black}
        />
      </group>
      <group
        position={[0, -0.428, 0]}
        rotation={[0.39, -Math.PI / 2, 0]}
        scale={[0.861, 0.881, 0.885]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials.uniform}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_40.geometry}
          material={materials["Outline_purple.001"]}
        />
        <group
          position={[0.658, -0.245, -0.059]}
          rotation={[-1.572, 1.465, 1.574]}
          scale={[0.269, 0.27, 0.199]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_42.geometry}
            material={materials["uniform.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_43.geometry}
            material={materials["Outline_purple.001"]}
          />
        </group>
      </group>
      <group
        position={[0.056, -0.443, 0.378]}
        rotation={[-1.487, 1.48, Math.PI / 2]}
        scale={4.686}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials.teeth}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials.Outline_black}
        />
      </group>
      <group rotation={[0, 0, -1.484]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_64.geometry}
          material={materials["hair.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials.Outline_black}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["Material.001"]}
        position={[-0.059, 0.33, 0.106]}
        rotation={[-0.71, 0.515, -0.802]}
        scale={3.601}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials["Material.002"]}
        position={[-0.059, -2.971, 0.106]}
        scale={6.096}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.lightning}
        position={[0.026, -0.537, -0.024]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.305}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.Material}
        position={[-0.058, 0.315, -1.531]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.black}
        position={[-0.034, 0, -0.001]}
        rotation={[Math.PI / 2, 0.098, 0]}
        scale={[1, 0.961, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.material}
        position={[-0.059, 0.33, 3.901]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={3.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_45.geometry}
        material={materials.Wrld}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.black}
        position={[-0.059, -0.279, 1.332]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49.geometry}
        material={materials.black}
        position={[-0.318, -0.453, -0.046]}
        rotation={[0.004, 0.001, 1.73]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_51.geometry}
        material={materials["face.001"]}
        position={[-0.034, 0, -0.001]}
        rotation={[Math.PI / 2, 0.098, 0]}
        scale={[1, 0.961, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials.black}
        position={[-0.058, 0.315, -0.031]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55.geometry}
        material={materials.black}
        position={[0.061, -0.298, 0.63]}
        rotation={[Math.PI / 2, 0.022, 0]}
        scale={0.131}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.empty_mat}
        position={[0.056, -0.438, 0.304]}
        rotation={[-Math.PI / 2, 1.48, Math.PI / 2]}
        scale={5.409}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        position={[0.175, -0.499, 0.416]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.022, 0.022, 0.015]}
      />
    </group>
  );
};

useGLTF.preload("/models/gojo.glb");

export default Gojo;
