import React from "react";
import { useGLTF } from "@react-three/drei";

const MobileMockup = (props) => {
  const { nodes, materials } = useGLTF("/models/mobile.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.545}
      >
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group
            name="Iphone_0"
            position={[-0.104, 1.448, -0.258]}
            scale={0.043}
          >
            <mesh
              name="Object_4"
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              name="Object_5"
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.Black}
            />
            <mesh
              name="Object_6"
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.Back}
            />
            <mesh
              name="Object_7"
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.GOLD}
            />
            <mesh
              name="Object_8"
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.BARRES}
            />
            <mesh
              name="Object_9"
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.Labber}
            />
            <mesh
              name="Object_10"
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.GLASS}
            />
            <mesh
              name="Object_11"
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.Lenscover}
            />
            <mesh
              name="Object_12"
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.material}
            />
            <mesh
              name="Object_13"
              castShadow
              receiveShadow
              geometry={nodes.Object_13.geometry}
              material={materials.Display}
            />
            <mesh
              name="Object_14"
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials["Lens.2"]}
            />
            <mesh
              name="Object_15"
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials.material_11}
            />
          </group>
          <group
            name="Iphone001_1"
            position={[-0.136, 1.448, 1.545]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.043}
          >
            <mesh
              name="Object_17"
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              name="Object_18"
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials.Black}
            />
            <mesh
              name="Object_19"
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.Back}
            />
            <mesh
              name="Object_20"
              castShadow
              receiveShadow
              geometry={nodes.Object_20.geometry}
              material={materials.GOLD}
            />
            <mesh
              name="Object_21"
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials.BARRES}
            />
            <mesh
              name="Object_22"
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.Labber}
            />
            <mesh
              name="Object_23"
              castShadow
              receiveShadow
              geometry={nodes.Object_23.geometry}
              material={materials.GLASS}
            />
            <mesh
              name="Object_24"
              castShadow
              receiveShadow
              geometry={nodes.Object_24.geometry}
              material={materials.Lenscover}
            />
            <mesh
              name="Object_25"
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.material}
            />
            <mesh
              name="Object_26"
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials.Display}
            />
            <mesh
              name="Object_27"
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials["Lens.2"]}
            />
            <mesh
              name="Object_28"
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials.material_11}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/mobile.glb");

export default MobileMockup;
